Update aios

diff --git a/aios b/aios
--- a/aios
+++ b/aios
@@ -23,10 +23,9 @@ echo -e "$(color "white"     "                                                  
 }
 
 make_directory() {
-mkdir -p "$BASE_DIR" || {
-    echo "Failed to create BASE_DIR: $BASE_DIR"
-    exit 1
-    }
+if [ ! -d "$BASE_DIR" ]; then
+    mkdir -p "$BASE_DIR" || { echo "Failed to create BASE_DIR"; exit 1; }
+fi
 }
 
 download_and_execute_common() {
