Update aios

diff --git a/aios b/aios
--- a/aios
+++ b/aios
@@ -48,9 +48,7 @@ delete_language() {
 }
 
 make_directory() {
-    if [ ! -d "$BASE_DIR" ]; then
-        mkdir -p "$BASE_DIR" || { echo "Failed to create BASE_DIR"; exit 1; }
-    fi
+    mkdir -p "$BASE_DIR"
 }
 
 download_and_execute_common() {
@@ -62,6 +60,15 @@ download_and_execute_common() {
         echo "Failed to source common-functions.sh"
         exit 1
     }
+}
+
+download_country_zone() {
+    wget --quiet -O "${BASE_DIR}/country-timezone.sh" "${BASE_URL}/country-timezone.sh"
+        echo "Failed to download country-timezone.sh"
+        exit 1
+    wget --quiet -O "${BASE_DIR}/country-zonename.sh" "${BASE_URL}/country-zonename.sh"
+        echo "Failed to download country-zonename.sh"
+        exit 1
 }
 
 download_openwrt_config() {
@@ -82,6 +89,7 @@ delete_language
 make_directory
 download_and_execute_common
 check_common "$1"
+download_country_zone
 download_openwrt_config
 banner
 execute_openwrt_config
